#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Product/Views/VProductBookDetail/_/Edit.cshtml")]
    public partial class _Areas_Product_Views_VProductBookDetail___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Product_Views_VProductBookDetail___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑预约信息视图";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Product/VProductBookDetail/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ProductBookDetailID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">预约编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductBookDetailID\"");

WriteLiteral(" name=\"ProductBookDetailID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 877), Tuple.Create("\"", 913)
            
            #line 22 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 885), Tuple.Create<System.Object, System.Int32>(Model.ProductBookDetailID
            
            #line default
            #line hidden
, 885), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品类型：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TypeName\"");

WriteLiteral(" name=\"TypeName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1103), Tuple.Create("\"", 1128)
            
            #line 25 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1111), Tuple.Create<System.Object, System.Int32>(Model.TypeName
            
            #line default
            #line hidden
, 1111), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ProductInfoId\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品信息id：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductInfoId\"");

WriteLiteral(" name=\"ProductInfoId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1372), Tuple.Create("\"", 1402)
            
            #line 30 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1380), Tuple.Create<System.Object, System.Int32>(Model.ProductInfoId
            
            #line default
            #line hidden
, 1380), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductName\"");

WriteLiteral(" name=\"ProductName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1597), Tuple.Create("\"", 1625)
            
            #line 33 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1605), Tuple.Create<System.Object, System.Int32>(Model.ProductName
            
            #line default
            #line hidden
, 1605), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ProductBookID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">预约订单编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductBookID\"");

WriteLiteral(" name=\"ProductBookID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1853), Tuple.Create("\"", 1883)
            
            #line 38 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1861), Tuple.Create<System.Object, System.Int32>(Model.ProductBookID
            
            #line default
            #line hidden
, 1861), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ProductID：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductID\"");

WriteLiteral(" name=\"ProductID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2064), Tuple.Create("\"", 2090)
            
            #line 41 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2072), Tuple.Create<System.Object, System.Int32>(Model.ProductID
            
            #line default
            #line hidden
, 2072), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ProductNo\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ProductNo：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductNo\"");

WriteLiteral(" name=\"ProductNo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2308), Tuple.Create("\"", 2334)
            
            #line 46 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2316), Tuple.Create<System.Object, System.Int32>(Model.ProductNo
            
            #line default
            #line hidden
, 2316), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">原价：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Price\"");

WriteLiteral(" name=\"Price\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2500), Tuple.Create("\"", 2522)
            
            #line 49 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2508), Tuple.Create<System.Object, System.Int32>(Model.Price
            
            #line default
            #line hidden
, 2508), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Num\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数量：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Num\"");

WriteLiteral(" name=\"Num\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2715), Tuple.Create("\"", 2735)
            
            #line 54 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2723), Tuple.Create<System.Object, System.Int32>(Model.Num
            
            #line default
            #line hidden
, 2723), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">销售价格：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SalePrice\"");

WriteLiteral(" name=\"SalePrice\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2910), Tuple.Create("\"", 2936)
            
            #line 57 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 2918), Tuple.Create<System.Object, System.Int32>(Model.SalePrice
            
            #line default
            #line hidden
, 2918), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Money\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">总金额：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Money\"");

WriteLiteral(" name=\"Money\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3136), Tuple.Create("\"", 3158)
            
            #line 62 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3144), Tuple.Create<System.Object, System.Int32>(Model.Money
            
            #line default
            #line hidden
, 3144), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">预约时间：</td><td>&nbsp;    <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onClick=\"WdatePicker({dateFmt:\'yyyy-MM-dd HH:mm:ss\'})\"");

WriteLiteral(" id=\"MakeTime\"");

WriteLiteral(" name=\"MakeTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3402), Tuple.Create("\"", 3483)
            
            #line 64 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 3410), Tuple.Create<System.Object, System.Int32>(Model.MakeTime==null?"":Model.MakeTime.ToString("yyyy-MM-dd HH:mm:ss")
            
            #line default
            #line hidden
, 3410), false)
);

WriteLiteral(" style=\"width:135px;\"");

WriteLiteral(">\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackField2\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">BackField2：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackField2\"");

WriteLiteral(" name=\"BackField2\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3654), Tuple.Create("\"", 3681)
            
            #line 69 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3662), Tuple.Create<System.Object, System.Int32>(Model.BackField2
            
            #line default
            #line hidden
, 3662), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">PurchasePrice：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PurchasePrice\"");

WriteLiteral(" name=\"PurchasePrice\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3874), Tuple.Create("\"", 3904)
            
            #line 72 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3882), Tuple.Create<System.Object, System.Int32>(Model.PurchasePrice
            
            #line default
            #line hidden
, 3882), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_StockNum\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">StockNum：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"StockNum\"");

WriteLiteral(" name=\"StockNum\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4118), Tuple.Create("\"", 4143)
            
            #line 77 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4126), Tuple.Create<System.Object, System.Int32>(Model.StockNum
            
            #line default
            #line hidden
, 4126), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ExchangeNeedBonus：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ExchangeNeedBonus\"");

WriteLiteral(" name=\"ExchangeNeedBonus\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4347), Tuple.Create("\"", 4381)
            
            #line 80 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4355), Tuple.Create<System.Object, System.Int32>(Model.ExchangeNeedBonus
            
            #line default
            #line hidden
, 4355), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_SaleDiscountPercent\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">SaleDiscountPercent：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SaleDiscountPercent\"");

WriteLiteral(" name=\"SaleDiscountPercent\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4639), Tuple.Create("\"", 4675)
            
            #line 85 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4647), Tuple.Create<System.Object, System.Int32>(Model.SaleDiscountPercent
            
            #line default
            #line hidden
, 4647), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"5\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">MinDiscountPercent：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MinDiscountPercent\"");

WriteLiteral(" name=\"MinDiscountPercent\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4882), Tuple.Create("\"", 4917)
            
            #line 88 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4890), Tuple.Create<System.Object, System.Int32>(Model.MinDiscountPercent
            
            #line default
            #line hidden
, 4890), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"5\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackField1\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">BackField1：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"BackField1\"");

WriteLiteral(" name=\"BackField1\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5139), Tuple.Create("\"", 5166)
            
            #line 93 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5147), Tuple.Create<System.Object, System.Int32>(Model.BackField1
            
            #line default
            #line hidden
, 5147), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">Comment：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Comment\"");

WriteLiteral(" name=\"Comment\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5341), Tuple.Create("\"", 5365)
            
            #line 96 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5349), Tuple.Create<System.Object, System.Int32>(Model.Comment
            
            #line default
            #line hidden
, 5349), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_MemberID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">MemberID：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MemberID\"");

WriteLiteral(" name=\"MemberID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5581), Tuple.Create("\"", 5606)
            
            #line 101 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5589), Tuple.Create<System.Object, System.Int32>(Model.MemberID
            
            #line default
            #line hidden
, 5589), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">创建时间：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"CreateUserID\"");

WriteLiteral(" name=\"CreateUserID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5787), Tuple.Create("\"", 5816)
            
            #line 104 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5795), Tuple.Create<System.Object, System.Int32>(Model.CreateUserID
            
            #line default
            #line hidden
, 5795), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_TotalMoney\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">TotalMoney：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TotalMoney\"");

WriteLiteral(" name=\"TotalMoney\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6039), Tuple.Create("\"", 6066)
            
            #line 109 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6047), Tuple.Create<System.Object, System.Int32>(Model.TotalMoney
            
            #line default
            #line hidden
, 6047), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"8\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">模型：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Models\"");

WriteLiteral(" name=\"Models\"");

WriteAttribute("value", Tuple.Create(" value=\"", 6233), Tuple.Create("\"", 6256)
            
            #line 112 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 6241), Tuple.Create<System.Object, System.Int32>(Model.Models
            
            #line default
            #line hidden
, 6241), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 118 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
   Write(RenderPage("~/Areas/Product/Views/VProductBookDetail/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 146 "..\..\Areas\Product\Views\VProductBookDetail\_\Edit.cshtml"
Write(RenderPage("~/Areas/Product/Views/VProductBookDetail/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
