#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    using Yamon.Module.UCenter.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/UCenter/Views/User/_/Edit.cshtml")]
    public partial class _Areas_UCenter_Views_User___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_UCenter_Views_User___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑用户";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/UCenter/User/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_UserName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_UserName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">用户名：</td><td>&nbsp;<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UserName\"");

WriteLiteral("  name=\"UserName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 844), Tuple.Create("\"", 869)
            
            #line 20 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
                                                                    , Tuple.Create(Tuple.Create("", 852), Tuple.Create<System.Object, System.Int32>(Model.UserName
            
            #line default
            #line hidden
, 852), false)
);

WriteLiteral("/><span");

WriteLiteral(" id=\"UserName_ShowValue\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
                                                                                                                                                                                                Write(Model.UserName);

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_PassWord\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_PassWord\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">密码：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"PassWord\"");

WriteLiteral(" name=\"PassWord\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1078), Tuple.Create("\"", 1103)
            
            #line 22 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1086), Tuple.Create<System.Object, System.Int32>(Model.PassWord
            
            #line default
            #line hidden
, 1086), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ConfirmPassword\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ConfirmPassword\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">密码确认：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"password\"");

WriteLiteral(" id=\"ConfirmPassword\"");

WriteLiteral(" name=\"ConfirmPassword\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1378), Tuple.Create("\"", 1410)
            
            #line 25 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1386), Tuple.Create<System.Object, System.Int32>(Model.ConfirmPassword
            
            #line default
            #line hidden
, 1386), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_TrueName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TrueName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">真实姓名：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TrueName\"");

WriteLiteral(" name=\"TrueName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1653), Tuple.Create("\"", 1678)
            
            #line 28 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1661), Tuple.Create<System.Object, System.Int32>(Model.TrueName
            
            #line default
            #line hidden
, 1661), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"20\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Email\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Email\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">Email：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Email\"");

WriteLiteral(" name=\"Email\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1894), Tuple.Create("\"", 1916)
            
            #line 31 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1902), Tuple.Create<System.Object, System.Int32>(Model.Email
            
            #line default
            #line hidden
, 1902), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" validType=\"email\"");

WriteLiteral("  [\'\'] maxlength=\"30\" style=\"width:200px\" />\r\n<span");

WriteLiteral(" title=\"用于接收系统提示消息\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DepartmentID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DepartmentID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">所属部门：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"DepartmentID\"");

WriteLiteral(" name=\"DepartmentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 2316), Tuple.Create("\"", 2383)
, Tuple.Create(Tuple.Create("", 2322), Tuple.Create("/api/UCenter/Department/EditTree?&Value=", 2322), true)
            
            #line 35 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
           , Tuple.Create(Tuple.Create("", 2362), Tuple.Create<System.Object, System.Int32>(Model.DepartmentID
            
            #line default
            #line hidden
, 2362), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 2384), Tuple.Create("\"", 2413)
            
            #line 35 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
                                         , Tuple.Create(Tuple.Create("", 2392), Tuple.Create<System.Object, System.Int32>(Model.DepartmentID
            
            #line default
            #line hidden
, 2392), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" required=\"true\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var DepartmentID_Value = \'");

            
            #line 37 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
                          Write(Model.DepartmentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#DepartmentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#DepartmentID').combotree('setValue',DepartmentID_Value);
            }
        });
    });
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_RoleID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_RoleID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">系统角色：</td><td>&nbsp;\r\n<select");

WriteLiteral(" id=\"RoleID\"");

WriteLiteral(" name=\"RoleID\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" multiple=\"true\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  style=\"width:200px\"");

WriteLiteral(">\r\n");

WriteLiteral("    ");

            
            #line 50 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowSelectOptions(ViewBag.DAL.NameValue_RoleID, Model.RoleID)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</select></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Tel\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Tel\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">手机号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Tel\"");

WriteLiteral(" name=\"Tel\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3246), Tuple.Create("\"", 3266)
            
            #line 53 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3254), Tuple.Create<System.Object, System.Int32>(Model.Tel
            
            #line default
            #line hidden
, 3254), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" validType=\"mobile\"");

WriteLiteral("  [\'\'] maxlength=\"30\" style=\"width:200px\" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Photo\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Photo\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">用户照片：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Photo\"");

WriteLiteral(" name=\"Photo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3505), Tuple.Create("\"", 3527)
            
            #line 56 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3513), Tuple.Create<System.Object, System.Int32>(Model.Photo
            
            #line default
            #line hidden
, 3513), false)
);

WriteLiteral("   class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral("/>\r\n<br/>\r\n<input");

WriteLiteral(" class=\"easyui-filebox\"");

WriteLiteral(" data-options=\"buttonText:\'浏览\',accept: \'image/*\',buttonAlign:\'left\'\"");

WriteLiteral(" id=\"Upload_Photo\"");

WriteLiteral(" name=\"Upload_Photo\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnPhoto_Upload\"");

WriteLiteral(" name=\"btnPhoto_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnPhoto_UploadClick()\"");

WriteLiteral("/>\r\n");

            
            #line 60 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
 if(!string.IsNullOrEmpty(Model.Photo)){

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_Photo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3959), Tuple.Create("\"", 3979)
            
            #line 61 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3965), Tuple.Create<System.Object, System.Int32>(Model.Photo
            
            #line default
            #line hidden
, 3965), false)
);

WriteLiteral(" style=\"height: 60px; \"");

WriteLiteral("/>\r\n");

            
            #line 62 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
}else{

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_Photo\"");

WriteAttribute("src", Tuple.Create(" src=\"", 4044), Tuple.Create("\"", 4064)
            
            #line 63 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4050), Tuple.Create<System.Object, System.Int32>(Model.Photo
            
            #line default
            #line hidden
, 4050), false)
);

WriteLiteral(" style=\"height: 60px; display: none; \"");

WriteLiteral("/>\r\n");

            
            #line 64 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    ///上传按钮事件
    function btnPhoto_UploadClick(){
        jQuery(""#myForm"").ajaxSubmit( {
            type: 'post',
            dataType: 'text',
            url: ""/api/SiteManage/UploadImage/Upload?FieldName=Photo&UploadFieldName=Upload_Photo&ModelID=User&ModuleID=UCenter"",
            beforeSubmit: function(formData, jqForm, options) {
                var queryString = jQuery.param(formData);
                if( jQuery(""Upload_Photo"").val()==""""){
                    alert(""请选择你要上传的图片！"");
                }
                return true;
            },
            success: function(msg) {
                eval(""var result=""+msg);
                if(result.Status==1){
                    jQuery(""#Photo"").val(result.returnValue);
                    alert(""上传成功!"");
                    $('#Upload_Photo').filebox('clear');
                    $('#Preview_Photo').attr('src',result.returnValue);
                }else{
                    alert(result.returnValue);
                }
            },
            error: function(error) {
            }
        });
    }
</script>
<span");

WriteLiteral(" title=\"用户照片\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_IsLockIP\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_IsLockIP\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否限制IP：</td><td>&nbsp;\r\n\r\n");

            
            #line 98 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsLockIP, "IsLockIP", Model.IsLockIP, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_LockIP\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_LockIP\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">限定IP：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"LockIP\"");

WriteLiteral(" name=\"LockIP\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:400px;height:60px\"");

WriteLiteral(">");

            
            #line 101 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
                                                                                            Write(Model.LockIP);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UserID\"");

WriteLiteral("  name=\"UserID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5893), Tuple.Create("\"", 5916)
            
            #line 103 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 5901), Tuple.Create<System.Object, System.Int32>(Model.UserID
            
            #line default
            #line hidden
, 5901), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 106 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
   Write(RenderPage("~/Areas/UCenter/Views/User/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
jQuery('input[name=IsLockIP]').bind('click', CheckConditions);
function CheckConditions(){
if(IsInCheckBox(document.myForm.IsLockIP,'1')){
jQuery('#Container_LockIP').show();
} 
else{ 
jQuery('#Container_LockIP').hide();
} 
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 141 "..\..\Areas\UCenter\Views\User\_\Edit.cshtml"
Write(RenderPage("~/Areas/UCenter/Views/User/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
