#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/Log/_/Show.cshtml")]
    public partial class _Areas_SiteManage_Views_Log___Show_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_Log___Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/SiteManage/Log/Show\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ModelID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">模型编号：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ModelID\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                       Write(Html.Raw(Model.ModelID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否成功：</td><td>&nbsp;<span");

WriteLiteral(" id=\"IsSuccess\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                         Write(Html.Raw(Model.IsSuccess));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_LogID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"LogID\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                   Write(Html.Raw(Model.LogID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">日志类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"LogType\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                       Write(Html.Raw(Model.LogType_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_LogContent\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">日志内容：</td><td>&nbsp;<span");

WriteLiteral(" id=\"LogContent\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                          Write(Html.Raw(Model.LogContent));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">操作人：</td><td>&nbsp;<span");

WriteLiteral(" id=\"UserID\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                     Write(Html.Raw(Model.UserID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_LogTime\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">操作时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"LogTime\"");

WriteLiteral(">");

            
            #line 31 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                       Write(Html.Raw(Model.LogTime));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">操作IP：</td><td>&nbsp;<span");

WriteLiteral(" id=\"UserIP\"");

WriteLiteral(">");

            
            #line 32 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                      Write(Html.Raw(Model.UserIP));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_LogKey\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">关键字：</td><td>&nbsp;<span");

WriteLiteral(" id=\"LogKey\"");

WriteLiteral(">");

            
            #line 35 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                     Write(Html.Raw(Model.LogKey));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">操作人：</td><td>&nbsp;<span");

WriteLiteral(" id=\"UserName\"");

WriteLiteral(">");

            
            #line 36 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                       Write(Html.Raw(Model.UserName));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Params\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">参数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Params\"");

WriteLiteral(">");

            
            #line 39 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
                                                    Write(Html.Raw(Model.Params));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 45 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
   Write(RenderPage("~/Areas/SiteManage/Views/Log/Extend/Model_ViewHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        关闭\r\n    </a>\r\n</div>\r\n");

            
            #line 53 "..\..\Areas\SiteManage\Views\Log\_\Show.cshtml"
Write(RenderPage("~/Areas/SiteManage/Views/Log/Extend/Model_ViewJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
