#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    
    #line 24 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    using System.Data;
    
    #line default
    #line hidden
    using System.IO;
    using System.Linq;
    using System.Net;
    
    #line 25 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    using System.Text;
    
    #line default
    #line hidden
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    using Yamon.Module.UCenter;
    using Yamon.Module.UCenter.Web;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/UCenter/Views/Position/_/Grid1.cshtml")]
    public partial class _Areas_UCenter_Views_Position___Grid1_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_UCenter_Views_Position___Grid1_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n\r\n");

            
            #line 3 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"tt\"");

WriteLiteral("></div>\r\n");

            
            #line 17 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
Write(RenderPage("~/Areas/UCenter/Views/Position/Extend/Model_GridHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" id=\"toolbar\"");

WriteLiteral(" style=\"padding: 5px; height: auto\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"searchForm\"");

WriteLiteral(" name=\"searchForm\"");

WriteLiteral(" action=\"\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n");

            
            #line 20 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
        
            
            #line default
            #line hidden
            
            #line 20 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
         foreach (ToolBar tool in ViewBag.ToolbarList)
{

            
            #line default
            #line hidden
WriteLiteral("    <a");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteAttribute("id", Tuple.Create(" id=\"", 709), Tuple.Create("\"", 731)
            
            #line 22 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
, Tuple.Create(Tuple.Create("", 714), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID
            
            #line default
            #line hidden
, 714), false)
);

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteAttribute("iconcls", Tuple.Create(" iconcls=\"", 758), Tuple.Create("\"", 785)
            
            #line 22 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
             , Tuple.Create(Tuple.Create("", 768), Tuple.Create<System.Object, System.Int32>(tool.ClassName
            
            #line default
            #line hidden
, 768), false)
);

WriteLiteral(" plain=\"true\"");

WriteAttribute("onclick", Tuple.Create(" onclick=\"", 799), Tuple.Create("\"", 873)
, Tuple.Create(Tuple.Create("", 809), Tuple.Create("T_", 809), true)
            
            #line 22 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                                        , Tuple.Create(Tuple.Create("", 811), Tuple.Create<System.Object, System.Int32>(tool.ToolBarID.Replace("-","")
            
            #line default
            #line hidden
, 811), false)
, Tuple.Create(Tuple.Create("", 844), Tuple.Create("ClickHandler();return", 844), true)
, Tuple.Create(Tuple.Create(" ", 865), Tuple.Create("false;", 866), true)
, Tuple.Create(Tuple.Create(" ", 872), Tuple.Create("", 872), true)
);

WriteLiteral(">");

            
            #line 22 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                                                                                                                                                                                  Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n");

            
            #line 23 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
}

            
            #line default
            #line hidden
DefineSection("scripts_toolbar", () => {

WriteLiteral("\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n");

            
            #line 29 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    
            
            #line default
            #line hidden
            
            #line 29 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
     foreach (ToolBar tool in ViewBag.ToolbarList)
    {

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" function T_");

            
            #line 31 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
              Write(tool.ToolBarID.Replace("-",""));

            
            #line default
            #line hidden
WriteLiteral("ClickHandler() {\r\n");

WriteLiteral("    ");

WriteLiteral("     ");

            
            #line 32 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
      Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("    ");

WriteLiteral("     return false;\r\n");

WriteLiteral("    ");

WriteLiteral(" }\r\n");

            
            #line 35 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    }

            
            #line default
            #line hidden
WriteLiteral("</script>\r\n");

});

WriteLiteral("\r\n        <span");

WriteLiteral(" id=\"span_DepartmentID\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">所属部门：\r\n<input");

WriteLiteral(" id=\"DepartmentID\"");

WriteLiteral(" name=\"DepartmentID\"");

WriteLiteral(" class=\"easyui-combotree\"");

WriteLiteral(" url=\"/api/UCenter/Department/EditTree?\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width: 150px;\"");

WriteLiteral("/>\r\n</span>\r\n<span");

WriteLiteral(" id=\"span_PositionName\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">岗位名称：<input");

WriteLiteral(" class=\"easyui-textbox\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PositionName\"");

WriteLiteral(" name=\"PositionName\"");

WriteLiteral(" value=\"\"");

WriteLiteral(" style=\"width:100px\"");

WriteLiteral(" /></span>\r\n<span");

WriteLiteral(" id=\"span_IsManager\"");

WriteLiteral("  style=\"height:24px;display: inline-block;\"");

WriteLiteral(">是否为部门主管：");

            
            #line 43 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                                                         Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IsManager, "IsManager","", "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</span>\r\n\r\n            <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-search\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">查询</a>\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" id=\"PagerButtons\"");

WriteLiteral("><label><input");

WriteLiteral(" id=\"BatchCheck\"");

WriteLiteral(" type=\"checkbox\"");

WriteLiteral(" />多选</label></div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        var _baseUrl = '/UCenter/Position';
var _apiUrl = '/api/UCenter/Position';
var _pageUrl = '';
var Data = {
BaseUrl: _baseUrl,
ApiUrl: _apiUrl,
FilterID: '',
DataUrl: _apiUrl + '/Grid1?'+_pageUrl,
CreateUrl: _baseUrl + '/Create?'+_pageUrl,
EditUrl: _baseUrl + '/Edit/{id}?'+_pageUrl,
ShowUrl: _baseUrl + '/Show/',
BatchDeleteUrl: _apiUrl + '/BatchDelete?'+_pageUrl,
DeleteUrl: _apiUrl + '/Delete?'+_pageUrl,
ModuleID: 'UCenter',
ModelID: 'Position',
PageSize: 20,
DialogWidth: 500,
DialogHeight: 500,
FieldShowType_Name_FieldName: '',
TreeField: '',
FieldShowType_Name_Title: '',
ItemName: ""岗位"",
PrimaryKey: 'PositionID',
SortField: 'PositionID',
OrderType: 'asc',
Height: 0,
UnAutoLoadGrid: ");

            
            #line 79 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
            Write(RequestHelper.GetInt("UnAutoLoadGrid"));

            
            #line default
            #line hidden
WriteLiteral(",\r\ncolumns: [[\r\n");

            
            #line 81 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID < 0)
    {

            
            #line default
            #line hidden
WriteLiteral("        ");

WriteLiteral("{field: \'");

            
            #line 85 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
               Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 85 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                           Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 85 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                                                                       Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("        ");

WriteLiteral("    ");

            
            #line 86 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
         Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("        ");

WriteLiteral("}},\r\n");

            
            #line 88 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral(@"
{field: 'PositionID', title: '岗位编号', sortable: true,width:100,align:'center'},
{field: 'DepartmentID_ShowValue', title: '所属部门', sortable: true,width:100,align:'left'},
{field: 'PositionName', title: '岗位名称', sortable: true,width:150,align:'left'},
{field: 'IsManager_ShowValue', title: '是否为部门主管', sortable: true,width:100,align:'center'},
{field: 'Responsibility', title: '岗位职责', sortable: true,width:100,align:'left',formatter: function(value, row, index){if(value){return '<div title=""'+value+'"">'+value+'</div>';}}},
{field: 'Tips', title: '备注', sortable: true,width:100,align:'left',formatter: function(value, row, index){if(value){return '<div title=""'+value+'"">'+value+'</div>';}}}
");

            
            #line 97 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
 foreach (ToolBar tool in ViewBag.ToolbarColumnList)
{
    if(tool.OrderID >= 0)
    {

            
            #line default
            #line hidden
WriteLiteral(",{field: \'");

            
            #line 101 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
        Write(tool.ToolBarID);

            
            #line default
            #line hidden
WriteLiteral("\', title: \'");

            
            #line 101 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                    Write(tool.ToolBarName);

            
            #line default
            #line hidden
WriteLiteral("\', sortable: false,width:");

            
            #line 101 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
                                                                                Write(tool.ToolBarName.Length*15+10);

            
            #line default
            #line hidden
WriteLiteral(",align:\'center\',formatter: function(value, row, index){\r\n");

WriteLiteral("    ");

            
            #line 102 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
 Write(Html.Raw(tool.OnClick));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

WriteLiteral("}}\r\n");

            
            #line 104 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
    }
}

            
            #line default
            #line hidden
WriteLiteral("]],\r\nfrozenColumns: [\r\n    [\r\n        {\r\n            field: \'ck\',\r\n            ch" +
"eckbox: true\r\n        }\r\n    ]\r\n],\r\ntoolbar: \'#toolbar\',\r\nsingleSelect: ");

            
            #line 116 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
          Write(RequestHelper.GetBool("SingleSelect",true).ToString().ToLower());

            
            #line default
            #line hidden
WriteLiteral("\r\n}\r\n    </script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.query.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/GridUtils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/SmartFormGrid.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Grid.js\"");

WriteLiteral("></script>\r\n");

            
            #line 124 "..\..\Areas\UCenter\Views\Position\_\Grid1.cshtml"
Write(RenderPage("~/Areas/UCenter/Views/Position/Extend/Model_GridJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

        }
    }
}
#pragma warning restore 1591
