
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的SystemConfigDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.SiteManage.Entity;

namespace Yamon.Module.SiteManage.DAL
{
    /// <summary>
    /// 系统配置实体类
    ///</summary>
    public partial class _SystemConfigDAL : BaseModelDAL<SystemConfig>
    {
        public _SystemConfigDAL():base("UCenter")
        {
        }





		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<SystemConfig> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ConfigKey,ConfigValue,Module";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ConfigKey,ConfigValue,Module";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual SystemConfig GetModelValue(SystemConfig model)
        {
            return model;
        }
		/// <summary>
        /// 设置系统配置实体(SystemConfig)的显示值
        /// </summary>
        /// <param name="model">系统配置实体(SystemConfig)</param>
        /// <returns>系统配置实体(SystemConfig)</returns>
		public virtual SystemConfig GetModelShowValue(SystemConfig model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if(clearValue)
			{
			}
			return model;
		}
		
		/// <summary>
        /// 设置系统配置实体(SystemConfig)的列表显示值
        /// </summary>
        /// <param name="model">系统配置实体(SystemConfig)</param>
        /// <returns>系统配置实体(SystemConfig)</returns>
		public virtual SystemConfig GetModelGridShowValue(SystemConfig model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual SystemConfig GetInfoByID(object id){
            SystemConfig model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 



      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时系统配置实体(SystemConfig)默认值
        /// </summary>
        /// <param name="model">系统配置实体(SystemConfig)</param>
        /// <returns>系统配置实体(SystemConfig)</returns>
		public virtual SystemConfig GetUpdateModelValue(SystemConfig model)
		{
			model.ConfigKey =null;
			model.Module = "SiteManage";
			return model;
		}		/// <summary>
        /// 设置编辑页面的系统配置实体(SystemConfig)默认值
        /// </summary>
        /// <param name="model">系统配置实体(SystemConfig)</param>
        /// <returns>系统配置实体(SystemConfig)</returns>
		public virtual SystemConfig GetEditFormDefaultValue(SystemConfig model)
		{
			model.Module="SiteManage";
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">系统配置实体(SystemConfig)</param>
        public virtual void EditFormValidator(SystemConfig model)
        {
			string value="";
			
			//SiteName验证
			value = model.SiteName!=null ? model.SiteName.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("系统名称不能为空！");
		            }
}
      #endregion

    }
}
