#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/API/DocIndex.cshtml")]
    public partial class _Areas_SiteManage_Views_API_DocIndex_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_API_DocIndex_cshtml()
        {
        }
        public override void Execute()
        {
            
            #line 1 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
  
    Layout = "~/Areas/SiteManage/Views/API/_Layout.cshtml";
    ViewBag.PageName = "DocIndex";

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" class=\"col-xs-12\"");

WriteLiteral(">\r\n    <h3");

WriteLiteral(" style=\"text-align: center;\"");

WriteLiteral(">");

            
            #line 6 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                                Write(Model.APIName);

            
            #line default
            #line hidden
WriteLiteral("</h3>\r\n    <!-- 这里开始是内容 -->\r\n");

WriteLiteral("    ");

            
            #line 8 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
Write(RenderPage("ShowAPI" + Model.APIType + ".cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script>\r\n        var myPage = {};\r\n        myPage.action = \'");

            
            #line 13 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                     Write(ViewContext.RouteData.Values["action"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.controller = \'");

            
            #line 14 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                         Write(ViewContext.RouteData.Values["controller"].ToString());

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.id = \'");

            
            #line 15 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                 Write(ViewContext.RouteData.Values["id"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.frame = \'");

            
            #line 16 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                    Write(Request["Frame"]);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.APIID = \'");

            
            #line 17 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                    Write(ViewBag.APIID);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.APIType = \'");

            
            #line 18 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
                      Write(Model.APIType);

            
            #line default
            #line hidden
WriteLiteral("\';\r\n        myPage.pageUrl = \'/SiteManage/API/DocIndex/?AppID=\';\r\n        myPage." +
"IsTool = 0;\r\n    </script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/json2.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/SiteManage/js/APIShow.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/SiteManage/js/RequestParamModel.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/SiteManage/js/ResponseParamModel.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/SiteManage/js/ErrorParamModel.js\"");

WriteLiteral("></script>\r\n");

            
            #line 27 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
    
            
            #line default
            #line hidden
            
            #line 27 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
     if (Model.APIType == 2)
    {

            
            #line default
            #line hidden
WriteLiteral("        <link");

WriteLiteral(" href=\"/Resources/JsLib/editormd/css/editormd.preview.min.css\"");

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"/Resources/JsLib/editormd/editormd.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"/Resources/JsLib/marked.min.js\"");

WriteLiteral("></script>\r\n");

WriteLiteral("        <script");

WriteLiteral(" src=\"/Resources/JsLib/prettify.min.js\"");

WriteLiteral("></script>\r\n");

            
            #line 33 "..\..\Areas\SiteManage\Views\API\DocIndex.cshtml"
    }

            
            #line default
            #line hidden
});

        }
    }
}
#pragma warning restore 1591
