
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的MemberMemberGradeController重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.Collections;
using System.IO;
using System.Linq.Expressions;
using System.Web;
using System.Web.Mvc;
using Yamon.Framework.DAL;
using Yamon.Module.SiteManage.Entity;
using Yamon.Module.Member.Entity;
using Yamon.Module.Member.DAL;
using Newtonsoft.Json;
using Yamon.Framework.Common;
using Yamon.Module.SiteManage.DAL;
using Yamon.Module.UCenter.DAL;
using Yamon.Framework.Common.IO;
using Yamon.Framework.MVC;
using Yamon.Module.Common;
using Yamon.Framework.NPOI;




namespace Yamon.Module.Member.Web.Controllers
{
    /// <summary>
    /// 会员列表
    /// </summary>
    public partial class _MemberMemberGradeController :BaseController
    {

        public MemberMemberGradeDAL dal = new MemberMemberGradeDAL();

        public virtual ActionResult Grid1()
        {
            return Index("Grid1","");
        }
        

        public ActionResult Index(string m,string filterId)
        {
            
            int userId = CookieHelper.GetCookieInt("UserID");
            string roleIds = CookieHelper.GetCookie("RoleIDList");
            string cityId = CookieHelper.GetCookie("CityID");
            string menuId = RequestHelper.GetRequestString("Menu");
            ViewBag.DAL = new MemberMemberGradeDAL();
            RolePurviewDAL rolePurviewDal = new RolePurviewDAL();
            ArrayList purviewList = rolePurviewDal.GetPurviewListByRoleID(roleIds);
            ToolBarDAL toolBarDal = new ToolBarDAL();
            List<ToolBar> toolbarList = toolBarDal.GetMyToolBarList(cityId, menuId, purviewList);
            ViewBag.ToolbarColumnList = toolbarList.Where(o => o.ToolbarType == "GridItem").ToList();
            ViewBag.ToolbarList=toolbarList.Where(o => ((o.ToolbarType == "Toolbar") || (o.ToolbarType == "CommonToolbar"))).ToList();

            string formPath = string.Format("~/Areas/Member/Views/MemberMemberGrade/_/{0}.cshtml", m);
            string myFormPath = string.Format("~/Areas/Member/Views/MemberMemberGrade/{0}.cshtml", m);
            //是否有自定义页面
            if (IOHelper.IsExist(Server.MapPath(myFormPath), FsoMethod.File))
            {
                formPath = myFormPath;
            }
            return View(formPath);
		}

        
        public virtual ActionResult Create()
        {
            return Form("Create");
        }

        public virtual ActionResult Edit(string id)
        {
            return Form("Edit", id);
        }

        public virtual ActionResult Show(string id)
        {
            return Form("Show", id);
        }

       public virtual ActionResult Form(string action, string id = "")
       {
           ViewBag.ID = id;
           MemberMemberGradeDAL dal=new MemberMemberGradeDAL();
           ViewBag.DAL=dal;
           MemberMemberGrade model=null;
           if (action == "Edit" || action == "Show")
           {
               model = dal.GetModelByID(id);
               model=dal.GetEditFormDefaultValue(model);
               model=dal.GetModelShowValue(model);
           }
           else
           {
               model = dal.GetCreateFormDefaultValue();
           }
           string formPath = string.Format("~/Areas/Member/Views/MemberMemberGrade/_/{0}.cshtml",action);
           string myFormPath = string.Format("~/Areas/Member/Views/MemberMemberGrade/{0}.cshtml", action);
           //是否有自定义页面
           if (IOHelper.IsExist(Server.MapPath(myFormPath), FsoMethod.File))
           {
               formPath = myFormPath;
           }
           return View(formPath,model);
       }

        

    }
}
