#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/SubPlan/_/Show.cshtml")]
    public partial class _Areas_SiteManage_Views_SubPlan___Show_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_SubPlan___Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/SiteManage/SubPlan/Show\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_SubPlanID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_SubPlanID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"SubPlanID\"");

WriteLiteral(">");

            
            #line 18 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                         Write(Html.Raw(Model.SubPlanID));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_PlanType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_PlanType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">计划类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"PlanType\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                        Write(Html.Raw(Model.PlanType));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Title\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Title\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">说明：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Title\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                             Write(Html.Raw(Model.Title));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_BeginDate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_BeginDate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">开始日期：</td><td>&nbsp;<span");

WriteLiteral(" id=\"BeginDate\"");

WriteLiteral(">");

            
            #line 21 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                           Write(Html.Raw(Model.BeginDate_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_EndDate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_EndDate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">结束日期：</td><td>&nbsp;<span");

WriteLiteral(" id=\"EndDate\"");

WriteLiteral(">");

            
            #line 22 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                     Write(Html.Raw(Model.EndDate_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DayExecuteTimeType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DayExecuteTimeType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天执行类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"DayExecuteTimeType\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                                        Write(Html.Raw(Model.DayExecuteTimeType));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_Interval\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_Interval\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">天间隔：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_Interval\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                   Write(Html.Raw(Model.Day_Interval));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_LoopNum\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_LoopNum\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天循环数量：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_LoopNum\"");

WriteLiteral(">");

            
            #line 25 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                   Write(Html.Raw(Model.Day_LoopNum));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_LoopType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_LoopType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天循环类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_LoopType\"");

WriteLiteral(">");

            
            #line 26 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                      Write(Html.Raw(Model.Day_LoopType));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_Time\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_Time\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天一次执行时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_Time\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                            Write(Html.Raw(Model.Day_Time));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_TimeList\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_TimeList\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天多次执行时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_TimeList\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                        Write(Html.Raw(Model.Day_TimeList));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ExecuteTimeType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ExecuteTimeType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">每天执行类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ExecuteTimeType\"");

WriteLiteral(">");

            
            #line 29 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                               Write(Html.Raw(Model.ExecuteTimeType));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_MonthLoopType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_MonthLoopType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月执行类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"MonthLoopType\"");

WriteLiteral(">");

            
            #line 30 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                        Write(Html.Raw(Model.MonthLoopType));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Month_Day_Interval\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Month_Day_Interval\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月执行间隔：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Month_Day_Interval\"");

WriteLiteral(">");

            
            #line 31 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                                       Write(Html.Raw(Model.Month_Day_Interval));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Month_Day_Num\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Month_Day_Num\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月执行天数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Month_Day_Num\"");

WriteLiteral(">");

            
            #line 32 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                        Write(Html.Raw(Model.Month_Day_Num));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Month_Week_Loop\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Month_Week_Loop\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月的第几周：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Month_Week_Loop\"");

WriteLiteral(">");

            
            #line 33 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                              Write(Html.Raw(Model.Month_Week_Loop));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Month_Week_Num\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Month_Week_Num\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月的循环周数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Month_Week_Num\"");

WriteLiteral(">");

            
            #line 34 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                            Write(Html.Raw(Model.Month_Week_Num));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Month_Interval\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Month_Interval\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">月的间隔数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Month_Interval\"");

WriteLiteral(">");

            
            #line 35 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                           Write(Html.Raw(Model.Month_Interval));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NoEndDate\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NoEndDate\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">无结束日期：</td><td>&nbsp;<span");

WriteLiteral(" id=\"NoEndDate\"");

WriteLiteral(">");

            
            #line 36 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                            Write(Html.Raw(Model.NoEndDate));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_TenDay_Interval\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TenDay_Interval\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">旬的第几天：</td><td>&nbsp;<span");

WriteLiteral(" id=\"TenDay_Interval\"");

WriteLiteral(">");

            
            #line 37 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                              Write(Html.Raw(Model.TenDay_Interval));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Week_Loop\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Week_Loop\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">指定星期的哪天：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Week_Loop\"");

WriteLiteral(">");

            
            #line 38 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                              Write(Html.Raw(Model.Week_Loop));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Week_LoopNum\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Week_LoopNum\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">周数：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Week_LoopNum\"");

WriteLiteral(">");

            
            #line 39 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                  Write(Html.Raw(Model.Week_LoopNum));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_BeginTime\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_BeginTime\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">天开始时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_BeginTime\"");

WriteLiteral(">");

            
            #line 40 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                        Write(Html.Raw(Model.Day_BeginTime));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Day_EndTime\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Day_EndTime\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">天结束时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Day_EndTime\"");

WriteLiteral(">");

            
            #line 41 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                                  Write(Html.Raw(Model.Day_EndTime));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_TendayList\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TendayList\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">旬：</td><td>&nbsp;<span");

WriteLiteral(" id=\"TendayList\"");

WriteLiteral(">");

            
            #line 42 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
                                                                                                           Write(Html.Raw(Model.TendayList));

            
            #line default
            #line hidden
WriteLiteral("</span></td></tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 46 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
   Write(RenderPage("~/Areas/SiteManage/Views/SubPlan/Extend/Model_ViewHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        关闭\r\n    </a>\r\n</div>\r\n");

            
            #line 54 "..\..\Areas\SiteManage\Views\SubPlan\_\Show.cshtml"
Write(RenderPage("~/Areas/SiteManage/Views/SubPlan/Extend/Model_ViewJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
