#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/Menu/_/Create.cshtml")]
    public partial class _Areas_SiteManage_Views_Menu___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_Menu___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建菜单";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/SiteManage/Menu/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_MenuName\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">菜单名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"MenuName\"");

WriteLiteral(" name=\"MenuName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 831), Tuple.Create("\"", 856)
            
            #line 22 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 839), Tuple.Create<System.Object, System.Int32>(Model.MenuName
            
            #line default
            #line hidden
, 839), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">上级菜单：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"ParentID\"");

WriteLiteral(" name=\"ParentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 1036), Tuple.Create("\"", 1106)
, Tuple.Create(Tuple.Create("", 1042), Tuple.Create("/api/SiteManage/Menu/EditTree?&iscombo=1&Value=", 1042), true)
            
            #line 26 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
          , Tuple.Create(Tuple.Create("", 1089), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1089), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1107), Tuple.Create("\"", 1132)
            
            #line 26 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
                                    , Tuple.Create(Tuple.Create("", 1115), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1115), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ParentID_Value = \'");

            
            #line 28 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
                      Write(Model.ParentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#ParentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#ParentID').combotree('setValue',ParentID_Value);
            }
        });
    });
</script>
</td>
</tr>
<tr");

WriteLiteral(" id=\"Container_OrderID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OrderID\"");

WriteLiteral(" name=\"OrderID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1618), Tuple.Create("\"", 1642)
            
            #line 42 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1626), Tuple.Create<System.Object, System.Int32>(Model.OrderID
            
            #line default
            #line hidden
, 1626), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">权限码：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PageCode\"");

WriteLiteral(" name=\"PageCode\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1809), Tuple.Create("\"", 1834)
            
            #line 45 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1817), Tuple.Create<System.Object, System.Int32>(Model.PageCode
            
            #line default
            #line hidden
, 1817), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"100\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n<span");

WriteLiteral(" title=\"为空时自动读取页面地址\"");

WriteLiteral("  class=\"easyui-tooltip\"");

WriteLiteral("><a");

WriteLiteral(" href=\"#\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" data-options=\"plain:true,iconCls:\'icon-help\'\"");

WriteLiteral("></a></span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_IconType\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">图标类型：</td><td>&nbsp;\r\n");

            
            #line 50 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_IconType, "IconType", Model.IconType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n<td>&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ClassName\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">CSS样式：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ClassName\"");

WriteLiteral(" name=\"ClassName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2440), Tuple.Create("\"", 2466)
            
            #line 56 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2448), Tuple.Create<System.Object, System.Int32>(Model.ClassName
            
            #line default
            #line hidden
, 2448), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ImageUrl\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">图标地址：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ImageUrl\"");

WriteLiteral(" name=\"ImageUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2692), Tuple.Create("\"", 2717)
            
            #line 61 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2700), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 2700), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Enabled\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">是否启用：</td><td>&nbsp;\r\n\r\n");

            
            #line 67 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_Enabled, "Enabled", Model.Enabled, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">打开方式：</td><td>&nbsp;\r\n");

            
            #line 70 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_OpenType, "OpenType", Model.OpenType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_MenuType\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">菜单类型：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n");

            
            #line 75 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_MenuType, "MenuType", Model.MenuType, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_LinkUrl\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">链接地址：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"LinkUrl\"");

WriteLiteral(" name=\"LinkUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3510), Tuple.Create("\"", 3534)
            
            #line 80 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3518), Tuple.Create<System.Object, System.Int32>(Model.LinkUrl
            
            #line default
            #line hidden
, 3518), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"500\"");

WriteLiteral(" style=\"width:410px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Tips\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">备注：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Tips\"");

WriteLiteral(" name=\"Tips\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:80px\"");

WriteLiteral(">");

            
            #line 85 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
                                                                                        Write(Model.Tips);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Toolbar\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">创建工具栏：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;");

            
            #line 89 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
                                                   Write(Html.Raw(MyHtmlHelper2.ShowCheckBox(ViewBag.DAL.NameValue_Toolbar, "Toolbar", Model.Toolbar, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td>\r\n</tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"MenuID\"");

WriteLiteral("  name=\"MenuID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4097), Tuple.Create("\"", 4120)
            
            #line 92 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4105), Tuple.Create<System.Object, System.Int32>(Model.MenuID
            
            #line default
            #line hidden
, 4105), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 95 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
   Write(RenderPage("~/Areas/SiteManage/Views/Menu/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
jQuery('input[name=IconType]').bind('click', CheckConditions);
function CheckConditions(){
if(IsInCheckBox(document.myForm.IconType,'css')){
jQuery('#Container_ClassName').show();
} 
else{ 
jQuery('#Container_ClassName').hide();
} 
if(IsInCheckBox(document.myForm.IconType,'image')){
jQuery('#Container_ImageUrl').show();
} 
else{ 
jQuery('#Container_ImageUrl').hide();
} 
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 136 "..\..\Areas\SiteManage\Views\Menu\_\Create.cshtml"
Write(RenderPage("~/Areas/SiteManage/Views/Menu/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
