#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Product/Views/OrderInfo/Summary.cshtml")]
    public partial class _Areas_Product_Views_OrderInfo_Summary_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Product_Views_OrderInfo_Summary_cshtml()
        {
        }
        public override void Execute()
        {
DefineSection("styles", () => {

WriteLiteral("\r\n    <link");

WriteAttribute("href", Tuple.Create(" href=\"", 27), Tuple.Create("\"", 69)
, Tuple.Create(Tuple.Create("", 34), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Product/css/Statistics.css")
, 34), false)
);

WriteLiteral(" rel=\"stylesheet\"");

WriteLiteral(" />\r\n");

});

DefineSection("scripts", () => {

WriteLiteral("\r\n\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 127), Tuple.Create("\"", 176)
, Tuple.Create(Tuple.Create("", 133), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Product/js/Summary.js?201609281507")
, 133), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/knockout/knockout.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteAttribute("src", Tuple.Create(" src=\"", 343), Tuple.Create("\"", 382)
, Tuple.Create(Tuple.Create("", 349), Tuple.Create<System.Object, System.Int32>(Href("~/Resources/JsLib/jquery.query.js")
, 349), false)
);

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/artTemplate/template.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.tablesorter.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" id=\"t-list\"");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(">\r\n        <tr>\r\n           \r\n            <td>{{name}}</td>\r\n            <td>{{to" +
"talmoney}}</td>\r\n            <td>{{refundmoney}}</td>\r\n            <td>{{total}}" +
"</td>\r\n        </tr>\r\n    </script>\r\n");

});

WriteLiteral("<div>\r\n    <div>\r\n        <span");

WriteLiteral(" style=\"font-size:14px; font-weight:bold;\"");

WriteLiteral(">选择日期:</span>\r\n\r\n        <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker({ dateFmt: \'yyyy-MM-dd\' })\"");

WriteLiteral(" id=\"StartTime\"");

WriteLiteral(" name=\"StartTime\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">\r\n        至\r\n        <input");

WriteLiteral(" class=\"Wdate\"");

WriteLiteral(" type=\"text\"");

WriteLiteral(" onclick=\"WdatePicker({ dateFmt: \'yyyy-MM-dd\' })\"");

WriteLiteral(" id=\"EndTime\"");

WriteLiteral(" name=\"EndTime\"");

WriteLiteral(" value=\"\"");

WriteLiteral(">&nbsp;\r\n        <button");

WriteLiteral(" class=\"btn btn-info\"");

WriteLiteral(" data-bind=\"click:clicklist\"");

WriteLiteral("> 查询</button>\r\n    </div>\r\n    <div>\r\n\r\n        <table");

WriteLiteral(" class=\"table table-striped tablesorter\"");

WriteLiteral(" id=\"tableList\"");

WriteLiteral(@">
            <thead>
                <tr>
                    
                    <th>名称</th>
                    <th>收入</th>
                    <th>退款</th>
                    <th>合计</th>
                </tr>
            </thead>
            <tbody");

WriteLiteral(" id=\"lines\"");

WriteLiteral("></tbody>\r\n        </table>\r\n    </div>\r\n</div>");

        }
    }
}
#pragma warning restore 1591
