#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Product/Views/ProductInfo/_/Create.cshtml")]
    public partial class _Areas_Product_Views_ProductInfo___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Product_Views_ProductInfo___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建商品";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Product/ProductInfo/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_ProductTypeId\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品类型：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"ProductTypeId\"");

WriteLiteral(" name=\"ProductTypeId\"");

WriteAttribute("url", Tuple.Create(" url=\"", 840), Tuple.Create("\"", 959)
, Tuple.Create(Tuple.Create("", 846), Tuple.Create("/api/Product/ProductType/EditTree_Models?Models=", 846), true)
            
            #line 23 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                      , Tuple.Create(Tuple.Create("", 894), Tuple.Create<System.Object, System.Int32>(RequestHelper.GetString("Models")
            
            #line default
            #line hidden
, 894), false)
, Tuple.Create(Tuple.Create("", 930), Tuple.Create("&Value=", 930), true)
            
            #line 23 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                 , Tuple.Create(Tuple.Create("", 937), Tuple.Create<System.Object, System.Int32>(Model.ProductTypeId
            
            #line default
            #line hidden
, 937), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 960), Tuple.Create("\"", 990)
            
            #line 23 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                                , Tuple.Create(Tuple.Create("", 968), Tuple.Create<System.Object, System.Int32>(Model.ProductTypeId
            
            #line default
            #line hidden
, 968), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" required=\"true\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ProductTypeId_Value = \'");

            
            #line 25 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                           Write(Model.ProductTypeId);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#ProductTypeId').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#ProductTypeId').combotree('setValue',ProductTypeId_Value);
            }
        });
    });
</script>
</td>
<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品编号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductInfoNo\"");

WriteLiteral(" name=\"ProductInfoNo\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1494), Tuple.Create("\"", 1524)
            
            #line 37 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1502), Tuple.Create<System.Object, System.Int32>(Model.ProductInfoNo
            
            #line default
            #line hidden
, 1502), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ProductName\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ProductName\"");

WriteLiteral(" name=\"ProductName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1760), Tuple.Create("\"", 1788)
            
            #line 42 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1768), Tuple.Create<System.Object, System.Int32>(Model.ProductName
            
            #line default
            #line hidden
, 1768), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"50\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">销售价格：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"SalePrice\"");

WriteLiteral(" name=\"SalePrice\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1964), Tuple.Create("\"", 1990)
            
            #line 45 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1972), Tuple.Create<System.Object, System.Int32>(Model.SalePrice
            
            #line default
            #line hidden
, 1972), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"10000000\"");

WriteLiteral("  precision=\"2\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_PurchasePrice\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">进货价格：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"PurchasePrice\"");

WriteLiteral(" name=\"PurchasePrice\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2228), Tuple.Create("\"", 2258)
            
            #line 50 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2236), Tuple.Create<System.Object, System.Int32>(Model.PurchasePrice
            
            #line default
            #line hidden
, 2236), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"10000000\"");

WriteLiteral("  precision=\"2\"");

WriteLiteral(" style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品库存：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"StockNum\"");

WriteLiteral(" name=\"StockNum\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2444), Tuple.Create("\"", 2469)
            
            #line 53 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2452), Tuple.Create<System.Object, System.Int32>(Model.StockNum
            
            #line default
            #line hidden
, 2452), false)
);

WriteLiteral(" class=\"easyui-numberbox\"");

WriteLiteral(" min=\"0\"");

WriteLiteral(" max=\"1000\"");

WriteLiteral("  style=\"width:200px;\"");

WriteLiteral("/>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Comment\"");

WriteLiteral(">\r\n<td");

WriteLiteral("  class=\"labeltd\"");

WriteLiteral(">备注：</td><td");

WriteLiteral("  colspan=\"3\"");

WriteLiteral(" >&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Comment\"");

WriteLiteral(" name=\"Comment\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:500px;height:80px\"");

WriteLiteral(">");

            
            #line 58 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                              Write(Model.Comment);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ImageUrl\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品图片：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ImageUrl\"");

WriteLiteral(" name=\"ImageUrl\"");

WriteAttribute("value", Tuple.Create(" value=\"", 2899), Tuple.Create("\"", 2924)
            
            #line 63 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 2907), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 2907), false)
);

WriteLiteral("   class=\"easyui-validatebox\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral("/>\r\n<br/>\r\n<input");

WriteLiteral(" class=\"easyui-filebox\"");

WriteLiteral(" data-options=\"buttonText:\'浏览\',accept: \'image/*\',buttonAlign:\'left\'\"");

WriteLiteral(" id=\"Upload_ImageUrl\"");

WriteLiteral(" name=\"Upload_ImageUrl\"");

WriteLiteral(" style=\"width: 200px;\"");

WriteLiteral(" />\r\n<input");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" type=\"button\"");

WriteLiteral(" id=\"btnImageUrl_Upload\"");

WriteLiteral(" name=\"btnImageUrl_Upload\"");

WriteLiteral(" value=\"上传\"");

WriteLiteral(" onclick=\"btnImageUrl_UploadClick()\"");

WriteLiteral("/>\r\n");

            
            #line 67 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
 if(!string.IsNullOrEmpty(Model.ImageUrl)){

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_ImageUrl\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3377), Tuple.Create("\"", 3400)
            
            #line 68 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3383), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 3383), false)
);

WriteLiteral(" style=\"height: 60px; \"");

WriteLiteral("/>\r\n");

            
            #line 69 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
}else{

            
            #line default
            #line hidden
WriteLiteral(" <br/>");

WriteLiteral("<img");

WriteLiteral(" id=\"Preview_ImageUrl\"");

WriteAttribute("src", Tuple.Create(" src=\"", 3468), Tuple.Create("\"", 3491)
            
            #line 70 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 3474), Tuple.Create<System.Object, System.Int32>(Model.ImageUrl
            
            #line default
            #line hidden
, 3474), false)
);

WriteLiteral(" style=\"height: 60px; display: none; \"");

WriteLiteral("/>\r\n");

            
            #line 71 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
 }

            
            #line default
            #line hidden
WriteLiteral("<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
    ///上传按钮事件
    function btnImageUrl_UploadClick(){
        jQuery(""#myForm"").ajaxSubmit( {
            type: 'post',
            dataType: 'text',
            url: ""/api/SiteManage/UploadImage/Upload?FieldName=ImageUrl&UploadFieldName=Upload_ImageUrl&ModelID=ProductInfo&ModuleID=Product"",
            beforeSubmit: function(formData, jqForm, options) {
                var queryString = jQuery.param(formData);
                if( jQuery(""Upload_ImageUrl"").val()==""""){
                    alert(""请选择你要上传的图片！"");
                }
                return true;
            },
            success: function(msg) {
                eval(""var result=""+msg);
                if(result.Status==1){
                    jQuery(""#ImageUrl"").val(result.returnValue);
                    alert(""上传成功!"");
                    $('#Upload_ImageUrl').filebox('clear');
                    $('#Preview_ImageUrl').attr('src',result.returnValue);
                }else{
                    alert(result.returnValue);
                }
            },
            error: function(error) {
            }
        });
    }
</script>
</td>
<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ExchangeNeedBonus\"");

WriteLiteral("  name=\"ExchangeNeedBonus\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4842), Tuple.Create("\"", 4876)
            
            #line 105 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 4850), Tuple.Create<System.Object, System.Int32>(Model.ExchangeNeedBonus
            
            #line default
            #line hidden
, 4850), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"SaleDiscountPercent\"");

WriteLiteral("  name=\"SaleDiscountPercent\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4952), Tuple.Create("\"", 4988)
            
            #line 105 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                                            , Tuple.Create(Tuple.Create("", 4960), Tuple.Create<System.Object, System.Int32>(Model.SaleDiscountPercent
            
            #line default
            #line hidden
, 4960), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"MinDiscountPercent\"");

WriteLiteral("  name=\"MinDiscountPercent\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5062), Tuple.Create("\"", 5097)
            
            #line 105 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                                                                                                                                                          , Tuple.Create(Tuple.Create("", 5070), Tuple.Create<System.Object, System.Int32>(Model.MinDiscountPercent
            
            #line default
            #line hidden
, 5070), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"UpdateTime\"");

WriteLiteral("  name=\"UpdateTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5155), Tuple.Create("\"", 5182)
            
            #line 105 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                                                                                                                                                                                                                                                       , Tuple.Create(Tuple.Create("", 5163), Tuple.Create<System.Object, System.Int32>(Model.UpdateTime
            
            #line default
            #line hidden
, 5163), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"CreateTime\"");

WriteLiteral("  name=\"CreateTime\"");

WriteAttribute("value", Tuple.Create(" value=\"", 5240), Tuple.Create("\"", 5267)
            
            #line 105 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
                                                                                                                                                                                                                                                                                                                                                                                                            , Tuple.Create(Tuple.Create("", 5248), Tuple.Create<System.Object, System.Int32>(Model.CreateTime
            
            #line default
            #line hidden
, 5248), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 108 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
   Write(RenderPage("~/Areas/Product/Views/ProductInfo/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
function CheckConditions(){
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 136 "..\..\Areas\Product\Views\ProductInfo\_\Create.cshtml"
Write(RenderPage("~/Areas/Product/Views/ProductInfo/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
