#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/API/Extend/Model_FormHtml.cshtml")]
    public partial class _Areas_SiteManage_Views_API_Extend_Model_FormHtml_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_API_Extend_Model_FormHtml_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteLiteral(" src=\"/Resources/JsLib/json2.js\"");

WriteLiteral("></script>\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"RequestParamHtml\"");

WriteLiteral(">\r\n    <div id=\"RequestParamDiv\">\r\n        <table id=\"RequestParamTable\" class=\"m" +
"ytable\" cellpadding=\"1\" width=\"100%\" cellspacing=\"0\" align=\"center\">\r\n          " +
"  <thead>\r\n                <tr style=\"text-align: center\">\r\n                    " +
"<th>参数名</th>\r\n                    <th>描述</th>\r\n                    <th>类型</th>\r\n" +
"                    <th>必需</th>\r\n                    <th>sign加密</th>\r\n          " +
"          <th>排序</th>\r\n                    <th>限制</th>\r\n                    <th " +
"/>\r\n                </tr>\r\n            </thead>\r\n            <tbody data-bind=\'f" +
"oreach: params\'>\r\n                <tr>\r\n                    <td><input class=\'re" +
"quired textbox\' style=\"\" data-bind=\'value: name, uniqueName: true, valueUpdate: " +
"\"afterkeydown\"\' /></td>\r\n                    <td><input class=\'required textbox\'" +
" data-bind=\'value: title, uniqueName: true, valueUpdate: \"afterkeydown\"\' /></td>" +
"\r\n                    <td>\r\n                        <select data-bind=\'value: ty" +
"pe, uniqueName: true, valueUpdate: \"afterkeydown\"\'>\r\n                           " +
" <option>string</option>\r\n                            <option>int</option>\r\n    " +
"                        <option>datetime</option>\r\n                            <" +
"option>double</option>\r\n                            <option>bool</option>\r\n     " +
"                       <option>float</option>\r\n                            <opti" +
"on>byte[]</option>\r\n                            <option>object</option>\r\n       " +
"                     <option>object[]</option>\r\n                        </select" +
">\r\n                    </td>\r\n                    <td style=\"text-align: center\"" +
"><input type=\"checkbox\" data-bind=\'checked: required, uniqueName: true, valueUpd" +
"ate: \"afterkeydown\"\' /></td>\r\n                    <td style=\"text-align: center\"" +
"><input type=\"checkbox\" data-bind=\'checked: sign, uniqueName: true, valueUpdate:" +
" \"afterkeydown\"\' /></td>\r\n                    <td><input class=\'required textbox" +
"\' style=\"width: 40px;\" data-bind=\'value: orderId, uniqueName: true, valueUpdate:" +
" \" afterkeydown\"\' /></td>\r\n                    <td><textarea data-bind=\'value: d" +
"esc, uniqueName: true, valueUpdate: \"afterkeydown\"\' style=\"width: 90%; height: 4" +
"0px;\"></textarea></td>\r\n                    <td><a href=\'#\' data-bind=\'click: $r" +
"oot.removeParam\'>删除</a></td>\r\n                </tr>\r\n            </tbody>\r\n     " +
"   </table>\r\n        <button type=\"button\" data-bind=\'click: addParam\'>增加</butto" +
"n>\r\n        <button type=\"button\" data-bind=\'click: addEntityParam\'>增加实体类参数</but" +
"ton>\r\n        <span data-bind=\"text: RequestJson\" style=\"display: none;\"> </span" +
">\r\n    </div>\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"ResponseParamHtml\"");

WriteLiteral(">\r\n    <div id=\"ResponseParamDiv\">\r\n        <table id=\"ResponseParamTable\" class=" +
"\"mytable\" cellpadding=\"1\" width=\"100%\" cellspacing=\"0\" align=\"center\">\r\n        " +
"    <thead>\r\n                <tr>\r\n                    <th>参数名</th>\r\n           " +
"         <th>描述</th>\r\n                    <th>类型</th>\r\n                    <th>排" +
"序</th>\r\n                    <th>备注</th>\r\n                    <th />\r\n           " +
"     </tr>\r\n            </thead>\r\n            <tbody data-bind=\'foreach: params\'" +
">\r\n                <tr style=\"background-color: #DDEBF9\">\r\n                    <" +
"td><input class=\'required textbox\' style=\"\" data-bind=\'value: name, uniqueName: " +
"true\' /></td>\r\n                    <td><input class=\'required textbox\' data-bind" +
"=\'value: title, uniqueName: true\' /></td>\r\n                    <td>\r\n           " +
"             <select data-bind=\'value: type, uniqueName: true\'>\r\n               " +
"             <option>string</option>\r\n                            <option>int</o" +
"ption>\r\n                            <option>datetime</option>\r\n                 " +
"           <option>double</option>\r\n                            <option>bool</op" +
"tion>\r\n                            <option>float</option>\r\n                     " +
"       <option>byte[]</option>\r\n                            <option>object</opti" +
"on>\r\n                            <option>object[]</option>\r\n                    " +
"    </select>\r\n                    </td>\r\n                    <td><input class=\'" +
"required textbox\' style=\"width: 40px;\" data-bind=\'value: orderId, uniqueName: tr" +
"ue, valueUpdate: \" afterkeydown\"\' /></td>\r\n                    <td><textarea dat" +
"a-bind=\'value: desc, uniqueName: true\' style=\"width: 90%; height: 40px;\"></texta" +
"rea></td>\r\n                    <td>\r\n                        <a href=\'#\' data-bi" +
"nd=\'click: $root.removeParam\'>删除</a>\r\n                        <a href=\'#\' data-b" +
"ind=\'click: $root.addChildParam\'>添加子参数</a><br />\r\n                        <a hre" +
"f=\'#\' data-bind=\'click: $root.addChildParamFromModel\'>添加实体类参数</a>\r\n             " +
"       </td>\r\n                </tr>\r\n                <tr data-bind=\'visible: chi" +
"ldren().length>0\'>\r\n                    <td colspan=\"5\">\r\n                      " +
"  <table class=\"mytable\" cellpadding=\"1\" width=\"100%\" cellspacing=\"0\" align=\"cen" +
"ter\">\r\n                            <tbody data-bind=\"foreach: children\">\r\n      " +
"                          <tr>\r\n                                    <td><input c" +
"lass=\'required textbox\' style=\"\" data-bind=\'value: name, uniqueName: true\' /></t" +
"d>\r\n                                    <td><input class=\'required textbox\' data" +
"-bind=\'value: title, uniqueName: true\' /></td>\r\n                                " +
"    <td>\r\n                                        <select data-bind=\'value: type" +
", uniqueName: true\'>\r\n                                            <option>string" +
"</option>\r\n                                            <option>int</option>\r\n   " +
"                                         <option>datetime</option>\r\n            " +
"                                <option>double</option>\r\n                       " +
"                     <option>float</option>\r\n                                   " +
"         <option>byte[]</option>\r\n                                        </sele" +
"ct>\r\n                                    </td>\r\n                                " +
"    <td><input class=\'required textbox\' style=\"width: 40px;\" data-bind=\'value: o" +
"rderId, uniqueName: true, valueUpdate: \" afterkeydown\"\' /></td>\r\n               " +
"                     <td><textarea data-bind=\'value: desc, uniqueName: true\' sty" +
"le=\"width: 90%; height: 40px;\"></textarea></td>\r\n                               " +
"     <td><a href=\'#\' data-bind=\'click: $root.removeChildParam\'>删除</a></td>\r\n    " +
"                            </tr>\r\n                            </tbody>\r\n       " +
"                 </table>\r\n                    </td>\r\n                </tr>\r\n   " +
"         </tbody>\r\n        </table>\r\n        <button type=\"button\" data-bind=\'cl" +
"ick: addParam\'>增加</button>\r\n        <span data-bind=\"text: ResponseJson\" style=\"" +
"display: none;\"> </span>\r\n    </div>\r\n</script>\r\n<script");

WriteLiteral(" type=\"text/html\"");

WriteLiteral(" id=\"ErrorCodeHtml\"");

WriteLiteral(@">
    <div id=""ErrorCodeDiv"">
        <table id=""ErrorCodeTable"" class=""mytable"" cellpadding=""1"" width=""100%"" cellspacing=""0"" align=""center"">
            <thead>
                <tr style=""text-align: center"">
                    <th>参数名</th>
                    <th>描述</th>
                </tr>
            </thead>
            <tbody data-bind='foreach: params'>
                <tr>
                    <td><input class='required textbox' style="""" data-bind='value: name, uniqueName: true, valueUpdate: ""afterkeydown""' /></td>
                    <td><textarea data-bind='value: desc, uniqueName: true, valueUpdate: ""afterkeydown""' style=""width: 90%; height: 40px;""></textarea></td>
                    <td><a href='#' data-bind='click: $root.removeParam'>删除</a></td>
                </tr>
            </tbody>
        </table>
        <button type=""button"" data-bind='click: addParam'>增加</button>
        <span data-bind=""text: RequestJson"" style=""display: none;""> </span>
    </div>
</script>
");

        }
    }
}
#pragma warning restore 1591
