#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Product/Views/VOrderDetail/_/Show.cshtml")]
    public partial class _Areas_Product_Views_VOrderDetail___Show_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Product_Views_VOrderDetail___Show_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------

            
            #line default
            #line hidden
WriteLiteral("\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #F6F6F6; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Product/VOrderDetail/Show\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_OrderDetailID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">订单明细ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"OrderDetailID\"");

WriteLiteral(">");

            
            #line 19 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                               Write(Html.Raw(Model.OrderDetailID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">状态：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Status\"");

WriteLiteral(">");

            
            #line 20 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                    Write(Html.Raw(Model.Status_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_PayStatus\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">支付状态：</td><td>&nbsp;<span");

WriteLiteral(" id=\"PayStatus\"");

WriteLiteral(">");

            
            #line 23 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.PayStatus_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">支付类型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"PayType\"");

WriteLiteral(">");

            
            #line 24 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                       Write(Html.Raw(Model.PayType_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_OrderID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">订单信息ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"OrderID\"");

WriteLiteral(">");

            
            #line 27 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.OrderID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品ID：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ProductID\"");

WriteLiteral(">");

            
            #line 28 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.ProductID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_ProductNo\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品编号：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ProductNo\"");

WriteLiteral(">");

            
            #line 31 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.ProductNo));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">原价：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Price\"");

WriteLiteral(">");

            
            #line 32 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                   Write(Html.Raw(Model.Price));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Num\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数量：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Num\"");

WriteLiteral(">");

            
            #line 35 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                 Write(Html.Raw(Model.Num));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">出售价格：</td><td>&nbsp;<span");

WriteLiteral(" id=\"SalePrice\"");

WriteLiteral(">");

            
            #line 36 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.SalePrice));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_Comment\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">备注：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Comment\"");

WriteLiteral(">");

            
            #line 39 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                     Write(Html.Raw(Model.Comment));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">备用字段1：</td><td>&nbsp;<span");

WriteLiteral(" id=\"BackField1\"");

WriteLiteral(">");

            
            #line 40 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                           Write(Html.Raw(Model.BackField1));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_BackField2\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">备用字段2：</td><td>&nbsp;<span");

WriteLiteral(" id=\"BackField2\"");

WriteLiteral(">");

            
            #line 43 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                           Write(Html.Raw(Model.BackField2));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">商品名称：</td><td>&nbsp;<span");

WriteLiteral(" id=\"ProductName\"");

WriteLiteral(">");

            
            #line 44 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                           Write(Html.Raw(Model.ProductName));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_TypeName\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">类型名称：</td><td>&nbsp;<span");

WriteLiteral(" id=\"TypeName\"");

WriteLiteral(">");

            
            #line 47 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                        Write(Html.Raw(Model.TypeName));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">模型：</td><td>&nbsp;<span");

WriteLiteral(" id=\"Models\"");

WriteLiteral(">");

            
            #line 48 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                    Write(Html.Raw(Model.Models_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_TotalMoney\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">总金额：</td><td>&nbsp;<span");

WriteLiteral(" id=\"TotalMoney\"");

WriteLiteral(">");

            
            #line 51 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                         Write(Html.Raw(Model.TotalMoney));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">销售时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"CreateTime\"");

WriteLiteral(">");

            
            #line 52 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                          Write(Html.Raw(Model.CreateTime));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_UpdateTime\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">修改时间：</td><td>&nbsp;<span");

WriteLiteral(" id=\"UpdateTime\"");

WriteLiteral(">");

            
            #line 55 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                          Write(Html.Raw(Model.UpdateTime));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">客户名称：</td><td>&nbsp;<span");

WriteLiteral(" id=\"MemberID\"");

WriteLiteral(">");

            
            #line 56 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                        Write(Html.Raw(Model.MemberID));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n</tr>\r\n<tr");

WriteLiteral(" id=\"Container_CreateUserID\"");

WriteLiteral(">\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">销售员：</td><td>&nbsp;<span");

WriteLiteral(" id=\"CreateUserID\"");

WriteLiteral(">");

            
            #line 59 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
                                                           Write(Html.Raw(Model.CreateUserID_ShowValue));

            
            #line default
            #line hidden
WriteLiteral("</span></td>\r\n<td");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">&nbsp;</td><td>&nbsp;</td>\r\n</tr>\r\n\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 65 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
   Write(RenderPage("~/Areas/Product/Views/VOrderDetail/Extend/Model_ViewHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        关闭\r\n    </a>\r\n</div>\r\n");

            
            #line 73 "..\..\Areas\Product\Views\VOrderDetail\_\Show.cshtml"
Write(RenderPage("~/Areas/Product/Views/VOrderDetail/Extend/Model_ViewJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");

        }
    }
}
#pragma warning restore 1591
