#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Product/Views/ProductType/_/Create.cshtml")]
    public partial class _Areas_Product_Views_ProductType___Create_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Product_Views_ProductType___Create_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="新建商品类型";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/Product/ProductType/Create\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_TypeName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_TypeName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"TypeName\"");

WriteLiteral(" name=\"TypeName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 853), Tuple.Create("\"", 878)
            
            #line 21 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 861), Tuple.Create<System.Object, System.Int32>(Model.TypeName
            
            #line default
            #line hidden
, 861), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"300\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_OrderID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_OrderID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OrderID\"");

WriteLiteral(" name=\"OrderID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1100), Tuple.Create("\"", 1124)
            
            #line 24 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1108), Tuple.Create<System.Object, System.Int32>(Model.OrderID
            
            #line default
            #line hidden
, 1108), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ParentID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ParentID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">上级类别：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"ParentID\"");

WriteLiteral(" name=\"ParentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 1340), Tuple.Create("\"", 1464)
, Tuple.Create(Tuple.Create("", 1346), Tuple.Create("/api/Product/ProductType/EditTree_Models?Models=", 1346), true)
            
            #line 28 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
           , Tuple.Create(Tuple.Create("", 1394), Tuple.Create<System.Object, System.Int32>(RequestHelper.GetString("Models")
            
            #line default
            #line hidden
, 1394), false)
, Tuple.Create(Tuple.Create("", 1430), Tuple.Create("&iscombo=1&Value=", 1430), true)
            
            #line 28 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
                                                                , Tuple.Create(Tuple.Create("", 1447), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1447), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1465), Tuple.Create("\"", 1490)
            
            #line 28 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
                                                                                          , Tuple.Create(Tuple.Create("", 1473), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1473), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ParentID_Value = \'");

            
            #line 30 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
                      Write(Model.ParentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#ParentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#ParentID').combotree('setValue',ParentID_Value);
            }
        });
    });
</script>
</td></tr>
<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"ProductTypeId\"");

WriteLiteral("  name=\"ProductTypeId\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1919), Tuple.Create("\"", 1949)
            
            #line 41 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
, Tuple.Create(Tuple.Create("", 1927), Tuple.Create<System.Object, System.Int32>(Model.ProductTypeId
            
            #line default
            #line hidden
, 1927), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"Models\"");

WriteLiteral("  name=\"Models\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1999), Tuple.Create("\"", 2022)
            
            #line 41 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
                                                                      , Tuple.Create(Tuple.Create("", 2007), Tuple.Create<System.Object, System.Int32>(Model.Models
            
            #line default
            #line hidden
, 2007), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 44 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
   Write(RenderPage("~/Areas/Product/Views/ProductType/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(@">
        jQuery(function() {
            CheckConditions();
jQuery('#Models').bind('change', CheckConditions);
function CheckConditions(){
if(jQuery('#Models').val() == 'Good'){
jQuery('#Container_ParentID').show();
} 
else{ 
jQuery('#Container_ParentID').hide();
} 
jQuery('fieldset').show(); 
jQuery(""fieldset"").each(function(){ 
if(jQuery('tr',this).length>0){
if(jQuery('tr:visible',this).length>0){jQuery(this).show()} else{jQuery(this).hide()}
}
});
}
;
        });
    </script>
");

WriteLiteral("    ");

            
            #line 79 "..\..\Areas\Product\Views\ProductType\_\Create.cshtml"
Write(RenderPage("~/Areas/Product/Views/ProductType/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
