#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.18444
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/Member/Views/MemberInfo/Extend/Model_FormJs.cshtml")]
    public partial class _Areas_Member_Views_MemberInfo_Extend_Model_FormJs_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_Member_Views_MemberInfo_Extend_Model_FormJs_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("<script");

WriteAttribute("src", Tuple.Create(" src=\"", 7), Tuple.Create("\"", 58)
, Tuple.Create(Tuple.Create("", 13), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Member/js/DatePicker.js?201609231748")
, 13), false)
);

WriteLiteral("></script>\r\n<script");

WriteAttribute("src", Tuple.Create(" src=\"", 78), Tuple.Create("\"", 125)
, Tuple.Create(Tuple.Create("", 84), Tuple.Create<System.Object, System.Int32>(Href("~/Static/Member/js/Member.js?201609231700")
, 84), false)
);

WriteLiteral(@"></script>
<script>
    MyForm.onBeforeSubmit = function () {

        $(""#BirthdayYear"").val($("".BirthdayYear"").val())

        var month = """";

        if ($('.BirthdayMonth').val().length == 1) {
            month = ""0"" + $('.BirthdayMonth').val() + ""-"";
        }
        else {
            month = $('.BirthdayMonth').val() + ""-"";
        }


        if ($("".Birthdaydays"").val().length == 1) {
            month = month + ""0"" + $("".Birthdaydays"").val();
        }
        else {
            month = month + $("".Birthdaydays"").val();
        }
        $(""#BirthdayMonthDay"").val(month)
        return true;
    }
</script>
");

        }
    }
}
#pragma warning restore 1591
