
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的方法，请在此文件的上级目录中的ProductConfigDAL重写(override)该方法。
//     如有问题联系zongeasy@qq.com
//
//</auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Data;
using System.ComponentModel;
using Yamon.Framework.DBUtility;
using System.Collections;
using Yamon.Framework.Common.DataBase;
using Yamon.Framework.Common;
using Yamon.Framework.Common.IO;
using System.IO;
using System.Linq.Expressions;
using Yamon.Framework.DAL;
using Yamon.Module.Product.Entity;

namespace Yamon.Module.Product.DAL
{
    /// <summary>
    /// 商品模块配置实体类
    ///</summary>
    public partial class _ProductConfigDAL : BaseModelDAL<ProductConfig>
    {
        public _ProductConfigDAL():base("UCenter")
        {
        }

		/// <summary>
        /// 是否开启打折功能（Menber）字段的数据集合（键值对）
        /// </summary>
		public MyNameValueCollection NameValue_Menber
		{
			get
			{
			    return Yamon.Module.SiteManage.DAL.DictTypeDAL.GetNameValueCollectionByID("d98af3cc-bf4e-4986-81dc-9d8725cb3eb4");

			}
		}




		/// <summary>
		/// 获取分页的数据实体列表
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>实体列表</returns>
		public virtual List<ProductConfig> GetEntityListByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ConfigKey,ConfigValue,Module";
			return GetEntityListByPage("1=1 "+ where, searchParams,order,fields, rows,page,topN,out totalRows);
		}

		/// <summary>
		/// 获取分页的数据列表DataTable
		///</summary>
		/// <param name="totalRows">记录总条数（out）</param>
		/// <param name="nv">页面传递参数集合</param>
		/// <param name="topN">数据条数</param>
		/// <param name="page">页码</param>
		/// <param name="rows">每页记录数</param>
		/// <param name="orderBy">排序</param>
		/// <returns>DataTable</returns>
		public virtual DataTable GetEntityTableByPage(out int totalRows,int topN = 0, int page=1,int rows=20,string orderBy="")
		{
			string order = "";
			if (!string.IsNullOrEmpty(orderBy))
			{
				order = orderBy;
			}
			object[] searchParams;
			string where = GetSearchSql("", out searchParams);
			string fields="ConfigKey,ConfigValue,Module";
			return GetEntityTableByPage("1=1 "+ where, searchParams,order,fields,rows,page,topN,out totalRows);
		}

		/// <summary>
        /// 拼接查询Sql语句及参数
        /// </summary>
        /// <param name="nv">页面传递的参数集合</param>
        /// <param name="notIn">排除字段</param>
        /// <param name="arrParam">out查询参数</param>
        /// <returns>查询Sql语句</returns>
		public virtual string GetSearchSql(string notIn,out object[] arrParam)
		{
			StringBuilder sb=new StringBuilder();
			string value="";
			string value1 = "";
			string value2 = "";
			ArrayList param=new ArrayList();
			arrParam=param.ToArray();
			return sb.ToString();

		}

		
	    public virtual ProductConfig GetModelValue(ProductConfig model)
        {
            return model;
        }
		/// <summary>
        /// 设置商品模块配置实体(ProductConfig)的显示值
        /// </summary>
        /// <param name="model">商品模块配置实体(ProductConfig)</param>
        /// <returns>商品模块配置实体(ProductConfig)</returns>
		public virtual ProductConfig GetModelShowValue(ProductConfig model,bool clearValue=false)
        {
            model=GetModelValue(model);
			if (model.Menber!=null)
			{
				model.Menber_ShowValue=NameValue_Menber.GetValues(model.Menber.ToString());
			}
			if(clearValue)
			{
				model.Menber = null;
			}
			return model;
		}
		
		/// <summary>
        /// 设置商品模块配置实体(ProductConfig)的列表显示值
        /// </summary>
        /// <param name="model">商品模块配置实体(ProductConfig)</param>
        /// <returns>商品模块配置实体(ProductConfig)</returns>
		public virtual ProductConfig GetModelGridShowValue(ProductConfig model){
			model=GetModelShowValue(model);
			return model;
        }

        public virtual ProductConfig GetInfoByID(object id){
            ProductConfig model = GetModelByID(id);
            model = GetModelShowValue(model);
            return model;
        } 



      #region 修改相关方法
		/// <summary>
        /// 设置更新入库时商品模块配置实体(ProductConfig)默认值
        /// </summary>
        /// <param name="model">商品模块配置实体(ProductConfig)</param>
        /// <returns>商品模块配置实体(ProductConfig)</returns>
		public virtual ProductConfig GetUpdateModelValue(ProductConfig model)
		{
			model.ConfigKey =null;
			model.Module = "Product";
			return model;
		}		/// <summary>
        /// 设置编辑页面的商品模块配置实体(ProductConfig)默认值
        /// </summary>
        /// <param name="model">商品模块配置实体(ProductConfig)</param>
        /// <returns>商品模块配置实体(ProductConfig)</returns>
		public virtual ProductConfig GetEditFormDefaultValue(ProductConfig model)
		{
			model.Module="Product";
			return model;
		}

		/// <summary>
        /// 编辑数据格式验证
        /// </summary>
        /// <param name="model">商品模块配置实体(ProductConfig)</param>
        public virtual void EditFormValidator(ProductConfig model)
        {
			string value="";
			
			//Menber验证
			value = model.Menber!=null ? model.Menber.ToString() : "";
		            if ( string.IsNullOrEmpty(value))
		            {
		             throw new Exception("是否开启打折功能不能为空！");
		            }
}
      #endregion

    }
}
