#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ASP
{
    using System;
    using System.Collections.Generic;
    using System.Data;
    using System.IO;
    using System.Linq;
    using System.Net;
    using System.Text;
    using System.Web;
    using System.Web.Helpers;
    using System.Web.Mvc;
    using System.Web.Mvc.Ajax;
    using System.Web.Mvc.Html;
    using System.Web.Routing;
    using System.Web.Security;
    using System.Web.UI;
    using System.Web.WebPages;
    using Yamon.Framework.Common;
    using Yamon.Module.SiteManage;
    using Yamon.Module.SiteManage.Entity;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    [System.Web.WebPages.PageVirtualPathAttribute("~/Areas/SiteManage/Views/API/_/Edit.cshtml")]
    public partial class _Areas_SiteManage_Views_API___Edit_cshtml : System.Web.Mvc.WebViewPage<dynamic>
    {
        public _Areas_SiteManage_Views_API___Edit_cshtml()
        {
        }
        public override void Execute()
        {
WriteLiteral("\r\n");

            
            #line 2 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
  
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由亚萌智能表单代码生成工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。除非此项目不再使用代码生成器生成。
//     如果想修改此文件的内容，请复制一份到此文件的上级目录进行修改
//
//     如有问题联系zongeasy@qq.com
//</auto-generated>
//------------------------------------------------------------------------------
    ViewBag.Title="编辑接口";

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n<div");

WriteLiteral(" region=\"center\"");

WriteLiteral(" border=\"true\"");

WriteLiteral(" style=\"padding: 10px; background: #FFFFFF; border: 1px solid #ccc;\"");

WriteLiteral(">\r\n    <form");

WriteLiteral(" id=\"myForm\"");

WriteLiteral(" name=\"myForm\"");

WriteLiteral(" action=\"/api/SiteManage/API/Edit\"");

WriteLiteral(" method=\"post\"");

WriteLiteral(">\r\n        <table");

WriteLiteral(" class=\"mytable\"");

WriteLiteral("  cellpadding=\"1\"");

WriteLiteral(" width=\"100%\"");

WriteLiteral(" cellspacing=\"0\"");

WriteLiteral(" align=\"center\"");

WriteLiteral(">\r\n<tr");

WriteLiteral(" id=\"Container_APIName\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_APIName\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">接口名称：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"APIName\"");

WriteLiteral(" name=\"APIName\"");

WriteAttribute("value", Tuple.Create(" value=\"", 842), Tuple.Create("\"", 866)
            
            #line 21 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 850), Tuple.Create<System.Object, System.Int32>(Model.APIName
            
            #line default
            #line hidden
, 850), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"200\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ParentID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ParentID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">上级类型：</td><td>&nbsp;\r\n\r\n<input");

WriteLiteral(" id=\"ParentID\"");

WriteLiteral(" name=\"ParentID\"");

WriteAttribute("url", Tuple.Create(" url=\"", 1100), Tuple.Create("\"", 1177)
, Tuple.Create(Tuple.Create("", 1106), Tuple.Create("/api/SiteManage/API/EditTree_APIType?&iscombo=1&Value=", 1106), true)
            
            #line 25 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                 , Tuple.Create(Tuple.Create("", 1160), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1160), false)
);

WriteAttribute("value", Tuple.Create(" value=\"", 1178), Tuple.Create("\"", 1203)
            
            #line 25 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                           , Tuple.Create(Tuple.Create("", 1186), Tuple.Create<System.Object, System.Int32>(Model.ParentID
            
            #line default
            #line hidden
, 1186), false)
);

WriteLiteral(" style=\"width: 200px\"");

WriteLiteral(" />\r\n<script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n    var ParentID_Value = \'");

            
            #line 27 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                      Write(Model.ParentID);

            
            #line default
            #line hidden
WriteLiteral(@"';
    jQuery(function() {
        jQuery('#ParentID').combotree(
        {
            onLoadSuccess:function(node, data) {
                jQuery('#ParentID').combotree('setValue',ParentID_Value);
            }
        });
    });
</script>
</td></tr>
<tr");

WriteLiteral(" id=\"Container_OrderID\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_OrderID\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">排序号：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"OrderID\"");

WriteLiteral(" name=\"OrderID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1704), Tuple.Create("\"", 1728)
            
            #line 39 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1712), Tuple.Create<System.Object, System.Int32>(Model.OrderID
            
            #line default
            #line hidden
, 1712), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral(" required=\"true\"");

WriteLiteral("  maxlength=\"4\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Url\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Url\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">接口地址：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"Url\"");

WriteLiteral(" name=\"Url\"");

WriteAttribute("value", Tuple.Create(" value=\"", 1950), Tuple.Create("\"", 1970)
            
            #line 42 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 1958), Tuple.Create<System.Object, System.Int32>(Model.Url
            
            #line default
            #line hidden
, 1958), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"200\"");

WriteLiteral(" style=\"width:90%\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_NeedUserLogin\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_NeedUserLogin\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">需要登录：</td><td>&nbsp;\r\n\r\n");

            
            #line 46 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowRadio(ViewBag.DAL.NameValue_NeedUserLogin, "NeedUserLogin", Model.NeedUserLogin, "&nbsp;&nbsp;")));

            
            #line default
            #line hidden
WriteLiteral("\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_Remark\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_Remark\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">接口描述：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"Remark\"");

WriteLiteral(" name=\"Remark\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:90%;height:40px\"");

WriteLiteral(">");

            
            #line 49 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                                                                          Write(Model.Remark);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_RequestType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_RequestType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">请求方式：</td><td>&nbsp;\r\n<select");

WriteLiteral(" id=\"RequestType\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" name=\"RequestType\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(">\r\n<option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择</option>\r\n");

            
            #line 54 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowSelectOptions(ViewBag.DAL.NameValue_RequestType, Model.RequestType)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</select></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_DataType\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_DataType\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">数据类型：</td><td>&nbsp;\r\n<select");

WriteLiteral(" id=\"DataType\"");

WriteLiteral(" class=\"easyui-combobox\"");

WriteLiteral(" name=\"DataType\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(">\r\n<option");

WriteLiteral(" value=\"\"");

WriteLiteral(">请选择</option>\r\n");

            
            #line 59 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
Write(Html.Raw(MyHtmlHelper2.ShowSelectOptions(ViewBag.DAL.NameValue_DataType, Model.DataType)));

            
            #line default
            #line hidden
WriteLiteral("\r\n</select></td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_RequestParam\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_RequestParam\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">请求参数：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"RequestParam\"");

WriteLiteral(" name=\"RequestParam\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:90%;height:80px\"");

WriteLiteral(">");

            
            #line 62 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                                                                                      Write(Model.RequestParam);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ResponseParam\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ResponseParam\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">返回参数：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"ResponseParam\"");

WriteLiteral(" name=\"ResponseParam\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:90%;height:80px\"");

WriteLiteral(">");

            
            #line 65 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                                                                                        Write(Model.ResponseParam);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ErrorCodeParam\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ErrorCodeParam\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">错误码：</td><td>&nbsp;\r\n<input");

WriteLiteral(" type=\"text\"");

WriteLiteral(" id=\"ErrorCodeParam\"");

WriteLiteral(" name=\"ErrorCodeParam\"");

WriteAttribute("value", Tuple.Create(" value=\"", 3839), Tuple.Create("\"", 3870)
            
            #line 68 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 3847), Tuple.Create<System.Object, System.Int32>(Model.ErrorCodeParam
            
            #line default
            #line hidden
, 3847), false)
);

WriteLiteral(" class=\"easyui-validatebox textbox\"");

WriteLiteral("  maxlength=\"30\"");

WriteLiteral(" style=\"width:200px\"");

WriteLiteral(" />\r\n</td></tr>\r\n<tr");

WriteLiteral(" id=\"Container_ResponseBody\"");

WriteLiteral("><td");

WriteLiteral(" id=\"Label_ResponseBody\"");

WriteLiteral(" class=\"labeltd\"");

WriteLiteral(">返回示例：</td><td>&nbsp;\r\n<textarea");

WriteLiteral(" id=\"ResponseBody\"");

WriteLiteral(" name=\"ResponseBody\"");

WriteLiteral(" class=\"easyui-validatebox\"");

WriteLiteral("  style=\"width:90%;height:80px\"");

WriteLiteral(">");

            
            #line 71 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                                                                                      Write(Model.ResponseBody);

            
            #line default
            #line hidden
WriteLiteral("</textarea>\r\n</td></tr>\r\n<input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"APIID\"");

WriteLiteral("  name=\"APIID\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4254), Tuple.Create("\"", 4276)
            
            #line 73 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
, Tuple.Create(Tuple.Create("", 4262), Tuple.Create<System.Object, System.Int32>(Model.APIID
            
            #line default
            #line hidden
, 4262), false)
);

WriteLiteral("/><input");

WriteLiteral(" type=\"hidden\"");

WriteLiteral(" id=\"APIType\"");

WriteLiteral("  name=\"APIType\"");

WriteAttribute("value", Tuple.Create(" value=\"", 4328), Tuple.Create("\"", 4352)
            
            #line 73 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
                                                , Tuple.Create(Tuple.Create("", 4336), Tuple.Create<System.Object, System.Int32>(Model.APIType
            
            #line default
            #line hidden
, 4336), false)
);

WriteLiteral("/>\r\n</table>\r\n\r\n");

WriteLiteral("        ");

            
            #line 76 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
   Write(RenderPage("~/Areas/SiteManage/Views/API/Extend/Model_FormHtml.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n    </form>\r\n</div>\r\n<div");

WriteLiteral(" region=\"south\"");

WriteLiteral(" border=\"false\"");

WriteLiteral(" style=\"text-align: right; background: #F6F6F6;height: 30px; line-height: 30px;\"");

WriteLiteral(">\r\n    <a");

WriteLiteral(" id=\"btnSubmit\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-ok\"");

WriteLiteral(" href=\"javascript:void(0)\"");

WriteLiteral(">确定</a>\r\n    <a");

WriteLiteral(" id=\"btnCancel\"");

WriteLiteral(" class=\"easyui-linkbutton\"");

WriteLiteral(" icon=\"icon-cancel\"");

WriteLiteral(" href=\"javascript:CloseDialog();\"");

WriteLiteral(">\r\n        取消\r\n    </a>\r\n</div>\r\n");

DefineSection("scripts", () => {

WriteLiteral("\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/jquery.form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Resources/JsLib/My97DatePicker/WdatePicker.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/Utils.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" src=\"/Static/v1/js/form.js\"");

WriteLiteral("></script>\r\n    <script");

WriteLiteral(" type=\"text/javascript\"");

WriteLiteral(">\r\n        jQuery(function() {\r\n            CheckConditions();\r\nfunction CheckCon" +
"ditions(){\r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQuery(\'#Container_CreateTime\'" +
").show();\r\n} \r\nelse{ \r\njQuery(\'#Container_CreateTime\').hide();\r\n} \r\nif(jQuery(\'#" +
"APIType\').val() == \'1\'){\r\njQuery(\'#Container_CreateUserID\').show();\r\n} \r\nelse{ \r" +
"\njQuery(\'#Container_CreateUserID\').hide();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'" +
"1\'){\r\njQuery(\'#Container_DataType\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Data" +
"Type\').hide();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQuery(\'#Container_Err" +
"orCodeParam\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_ErrorCodeParam\').hide();\r\n" +
"} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQuery(\'#Container_IsDelete\').show();\r" +
"\n} \r\nelse{ \r\njQuery(\'#Container_IsDelete\').hide();\r\n} \r\nif(jQuery(\'#APIType\').va" +
"l() == \'1\'){\r\njQuery(\'#Container_NeedUserLogin\').show();\r\n} \r\nelse{ \r\njQuery(\'#C" +
"ontainer_NeedUserLogin\').hide();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQue" +
"ry(\'#Container_Remark\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Remark\').hide();" +
"\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQuery(\'#Container_RequestParam\').sh" +
"ow();\r\n} \r\nelse{ \r\njQuery(\'#Container_RequestParam\').hide();\r\n} \r\nif(jQuery(\'#AP" +
"IType\').val() == \'1\'){\r\njQuery(\'#Container_RequestType\').show();\r\n} \r\nelse{ \r\njQ" +
"uery(\'#Container_RequestType\').hide();\r\n} \r\nif((jQuery(\'#APIType\').val() == \'1\'|" +
"|jQuery(\'#APIType\').val() == \'2\')){\r\njQuery(\'#Container_ResponseBody\').show();\r\n" +
"} \r\nelse{ \r\njQuery(\'#Container_ResponseBody\').hide();\r\n} \r\nif(jQuery(\'#APIType\')" +
".val() == \'1\'){\r\njQuery(\'#Container_ResponseParam\').show();\r\n} \r\nelse{ \r\njQuery(" +
"\'#Container_ResponseParam\').hide();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\nj" +
"Query(\'#Container_Status\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Status\').hide" +
"();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\'){\r\njQuery(\'#Container_UpdateTime\').s" +
"how();\r\n} \r\nelse{ \r\njQuery(\'#Container_UpdateTime\').hide();\r\n} \r\nif(jQuery(\'#API" +
"Type\').val() == \'1\'){\r\njQuery(\'#Container_UpdateUserID\').show();\r\n} \r\nelse{ \r\njQ" +
"uery(\'#Container_UpdateUserID\').hide();\r\n} \r\nif(jQuery(\'#APIType\').val() == \'1\')" +
"{\r\njQuery(\'#Container_Url\').show();\r\n} \r\nelse{ \r\njQuery(\'#Container_Url\').hide()" +
";\r\n} \r\njQuery(\'fieldset\').show(); \r\njQuery(\"fieldset\").each(function(){ \r\nif(jQu" +
"ery(\'tr\',this).length>0){\r\nif(jQuery(\'tr:visible\',this).length>0){jQuery(this).s" +
"how()} else{jQuery(this).hide()}\r\n}\r\n});\r\n}\r\n;\r\n        });\r\n    </script>\r\n");

WriteLiteral("    ");

            
            #line 194 "..\..\Areas\SiteManage\Views\API\_\Edit.cshtml"
Write(RenderPage("~/Areas/SiteManage/Views/API/Extend/Model_FormJs.cshtml"));

            
            #line default
            #line hidden
WriteLiteral("\r\n");

});

WriteLiteral("\r\n");

        }
    }
}
#pragma warning restore 1591
